### ISSUE TITLE
Various issues with ore proccessing

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Modbder/EssentialCraft3#12]
EC3 4.6.1710.35

The magmatic smeltery consumes lava even if it has only used a fraction of a bucket.

There doesn't seem to be any way to input the molten ore into the second processing slot of the magmatic smeltery. Thus, automation f it is almost impossible unless you use the magical inventory manager.

The magical furnace(The ore processing for two ingots an ore) can be exported from, but not imputed. Thus, automation is impossible.

**Comment by Modbder** [comment]
You should be able to import into those slots - hold control key in the inventories to see the side the slots are accessible from.

**Comment by TheMadmanofChaos** [comment]
These screen shots show that isn't possible.
http://i.imgur.com/31QvvfJ.png
http://i.imgur.com/NR3dKwe.png
