### ISSUE TITLE
Guide book line wrap need improvements

### ISSUE THREAD

**Issue by Joccob** [Modbder/EssentialCraft3#14]
EssentialCraft v4.5.1710.223

I really like this mod and I actually started the translation. But then I meet some problems.
First, Chinese is a special language which does not need space to separate words. Thus the words always go out of the book. 
Second, this also happens when I'm using English. And sometimes the lines warp are just wired. 
![qq 20150721085338](https://cloud.githubusercontent.com/assets/11893599/8791088/7158eaac-2f88-11e5-98e3-ed9f943b05f0.png)
![qq 20150721085332](https://cloud.githubusercontent.com/assets/11893599/8791092/7e64bbea-2f88-11e5-9b1f-7cd7706bee16.png)![qq 20150721085324](https://cloud.githubusercontent.com/assets/11893599/8791095/81ce1b82-2f88-11e5-9d39-bae3db6eed59.png)

I dont know anything about coding, but I think it is possible to automatically change line when the words reach the border of the book (like Thaumnomicon and TiC guide book). 

All I want to say is that the book is the way for players to know about the mod. So it is kinda important to enhance the user experience. I would be really appreciated if you can make some improvement. And thank you for bring us such a great mod.

**Comment by Modbder** [comment]
I'll see what can be done with that issue. Most likely I will just use the vanilla's way of rendering text in books.

**Comment by PatchouliHina** [comment]
I wonder if it can use some specific sign to get warped. I remembered some lang file using sign such as '!n' to get a new line, just like some effectors "BR" or "Line". Then we can easily control the fomat of the text.
