### ISSUE TITLE
Crash When Opening Inventory

### ISSUE THREAD

**Issue by catzs** [Modbder/EssentialCraft3#15]
http://pastebin.com/HXmWPzje
Title. 
Version: 4.5.1710.208

**Comment by Modbder** [comment]
Something is trying to render one of EC3's items with a metadata of 8192. And fails - as expected, there is just no such metadata. Make sure that your player.dat file is fine - there should be no such item in there. If there is delete it, any inventory editor/mcedit or even NBT editor is enough. If the item is not in your inventory then I need an info of it's location - NEI, Another inventory, etc. For now that does not seem much like EC3's issue.
