### ISSUE TITLE
Moon Well is not producing MRU

### ISSUE THREAD

**Issue by learntechguy** [Modbder/EssentialCraft3#19]
Once placed with a clear view of the sky (tested at different levels), the Moon Well won't generate any MRU during the night. It detects the different lunar phases, but the MRU count remains at zero.

**Comment by Modbder** [comment]
Try placing it right above the bedrock.

**Comment by learntechguy** [comment]
That's exactly where I've had it for a few days now. Not a single MRU.

It's also worth mentioning I created a 64x64 opening in creative mode just to check if my hole was wide enough and placed a bunch of wells. None of them worked during the full moon.
