### ISSUE TITLE
Portal to Hoanna keeps creating a portal to the Nether

### ISSUE THREAD

**Issue by learntechguy** [Modbder/EssentialCraft3#21]
I created a Nether portal, right clicked it with the decoded wind tablet and I appeared in Hoanna. Everything alright until here. However, in Hoanna there is no portal to go back home. The only portal that has been created leads to the Nether. I went back to the Overworld through an old portal I had and the portal in my base hasn't changed. It leads to Hoanna. Is this expected behaviour or you should be able to go back to the Overworld from Hoanna?

I can also confirm this happens when I try it in creative. The portal in Hoanna leads to the Nether. Oh, and for some reason I was able to create a portal to Hoanna in Hoanna and break the game :D

**Comment by Modbder** [comment]
Yes, the portal in Hoanna is a portal to the nether, where you can take a portal to the overworld and your Hoanna portal will stay. This is intentional.

**Comment by learntechguy** [comment]
But if I wouldn't have had a portal before I would be trapped between the Nether and Hoanna.

**Comment by Modbder** [comment]
Not true, since exiting out of the nether using the nether portal automatically creates a corresponding portal in the overworld if none was found. The only way to get trapped is to create a hoanna portal out of that nether portal, but since Hoanna generates as the overworld does it is possible to find both obsidian and flint+iron there to make a portal back.

**Comment by learntechguy** [comment]
I understand what you mean. However, since the mod did not require me to go to the Nether, I used the only portal I had in the Overworld to go to Hoanna. If I was playing alone or with friends that did not go to the Nether yet (and therefore have a portal already), the mod would have had me trapped between Hoanna and the Nether. I would suggest maybe changing some of the recipes so they require something from the Nether (i.e. magma cream instead of ender pearls, or netherrack instead of stone). That way you force people to create a portal in the first place. Anyways, thanks a lot for taking the time to explain it.

**Comment by TheMadmanofChaos** [comment]
Something I should point out: You can't make Nether portals in Hoanna. Tried it a few versions ago, so unless that has changed you are stuck in Hoanna if you can't find the original portal. You can build the basic frame, but lighting it does nothing but start a fire.
