### ISSUE TITLE
Cold Distillator does not produce XP

### ISSUE THREAD

**Issue by learntechguy** [Modbder/EssentialCraft3#22]
Hi there! I tried to make a mob farm only using EC3 with the Cold Distillator (+bonus MRU!) and the mobs that are being killed only drop items, not XP. Since we already have the Mob Duplicator for the loot, I was wondering if this was intended or not (~~I can't see how to produce XP otherwise~~ I still have to test the tesla coil)

**Comment by Modbder** [comment]
This is intended - the cold distillator's damage is not direct/fake player type.

**Comment by learntechguy** [comment]
Oooh, so my monster freezer needs a tesla coil then... Thanks for the clarification!
