### ISSUE TITLE
Ender Generator and Angry Endermen

### ISSUE THREAD

**Issue by learntechguy** [Modbder/EssentialCraft3#23]
I have noticed the Ender Generator only attracts Endermen but not Angry Endermen from HEE. Would it be difficult to make them compatible with the Generator? This would give it more usability in packs containing DartCraft or in the case of HorizonsII, Hardcore Ender Expansion.

**Comment by Modbder** [comment]
Is more of a HEE issue - why would it create endermen not extending the standart EntityEnderman class in the first place? I can add the compatibility, sure.

**Comment by learntechguy** [comment]
Thanks - I will raise these issues to chylex too.
