### ISSUE TITLE
glitch with router reborn and EC3

### ISSUE THREAD

**Issue by Eidelmaim** [Modbder/EssentialCraft3#25]
this is not exactly a duplication glitch per say, but i feel it is worth taking note of. while using the Essential Craft 3 mod to handle sorting needs, a player on my server discovered that you can change any item from one type to another using the following method in the video i created showing it. I also posted this issue to the Router Reborn for them to review as well. the bug can be found in the Horizons 1.1.0 mod pack using Router Reborn v 1.7.10-1.2.0.31-universal

https://www.youtube.com/watch?v=-JdzFxS2V64
additional video i made showing set up and the glitch.
https://www.youtube.com/watch?v=Pi1XvKzj0pw

**Comment by Modbder** [comment]
Can you please provide me with a version of EC3 you are using? Since I'm pretty sure that I've fixed 'those' types of duplication glitches in da7989e9714281b2c4e86ce32e0a69a6c9447f77, unless the problem is on the RR's side, which I don't think it is.

**Comment by Eidelmaim** [comment]
Horizons Daybreaker 1.1.0
Essentials Craft 3 4.6.1710.35
Router Reborn 1.7.10-1.2.0.31-universal

**Comment by Modbder** [comment]
I've suspected that. Try updating to 4.6.1710.42 or 4.6.1710.63

**Comment by Eidelmaim** [comment]
the pack is a FTB release, i can not update my server without forcing all my users to update thier own client sided

**Comment by Modbder** [comment]
I mean try updating locally, in a test client or something to see if the issue stays.

**Comment by Eidelmaim** [comment]
will do

**Comment by Eidelmaim** [comment]
issue is indeed resolved in 4.6.1710.63 in SP, have not tested on a local server, but with a unforeseen side effect possibly, the item has no where to go and sits in the shift clicked slot and completely drains all MRU from the block, and the block will not regain any MRU untill you take the item out of that slot. is this intended ?

**Comment by Modbder** [comment]
This is not intended, but is actually not that big of an issue. I will add a check so MRU won't get drained if the item has nowhere to go. Good to know that the main issue is resolved

**Comment by Eidelmaim** [comment]
also looks like ther emight be a layers issue here.... http://prntscr.com/8aw06y but i dont see this as a major thing

**Comment by Modbder** [comment]
Oh, that happens due to the search bar being rendered above everything else. I forgot to change the zLevel there.

**Comment by Eidelmaim** [comment]
no worries, like i said, not a big thing :) thanks for your assistance though !
