### ISSUE TITLE
Bug with EC3 and RFTools

### ISSUE THREAD

**Issue by Eidelmaim** [Modbder/EssentialCraft3#26]
this bug involves the RFTools Modular Storage and the Magical inventory management system. if you have a modular storage bound to the magical system and you remove the storage module from the modular storage via the magical inventory manager screen, the storage module will lose tis data and all items stored on it are erased, please see video.

https://www.youtube.com/watch?v=Ltp5En3Ae4Q

**Comment by Modbder** [comment]
The same as issue #16 . Since I'm using the ItemStack.copy() method which copies all the data on the item(including NBT) I would suggest that the problem is somewhere on FR tools side.

**Comment by Eidelmaim** [comment]
Hey Mobder, thought i would show you the responce from McJty over at RFTools concerning this bug....
https://github.com/McJty/RFTools/issues/310

**Comment by Modbder** [comment]
Yes, I do not have the check for exporting the item out of the inventory... I only have stackSize checks, hmm... That might be not necessary for most inventories, but if that is the case here - sure, I will add a simple check.
