### ISSUE TITLE
Magical Chest breaks OpenComputers recipes

### ISSUE THREAD

**Issue by foone** [Modbder/EssentialCraft3#28]
When EssentialCraft3 and OpenComputers are installed, the recipes for computer cases which require chests change to only allow EssentialCraft3 Magical Chests. 

There was [an OpenComputers bug report for this](https://github.com/MightyPirates/OpenComputers/issues/1399), but they say they just use the oredict chest, so EssentialCraft3 must be doing something odd here.

**Comment by Modbder** [comment]
I am not 'replacing' an oredict entry. I am just writing my chests to oredict as "chest".
https://github.com/Modbder/EssentialCraft3/blob/master/java/ec3/common/registry/OreDictionaryRegistry.java#L45
As you can see I am not deleting the vanilla chest from the oredict, so OC's recipes should still be able to accept normal chests. I've tested that and it works just fine for mods I've tested it with...

**Comment by foone** [comment]
Yeah, that makes sense. I'm looking closer into OpenComputers code, it must be on their end.
