### ISSUE TITLE
Vanilla recipes being replaced with EC3 blocks

### ISSUE THREAD

**Issue by ligerzero459** [Modbder/EssentialCraft3#29]
Modpack: Horizons: Daybreaker 1.2.0
Mod version: EssentialCraft 4.6.63

Since upgrading from EC3 4.6.35 to 4.6.63, random recipes have vanilla glass or vanilla chests replaced with the EC3 version. I encountered the issue with recipes in both OpenComputers and Matter Overdrive. Possibly related to OreDictionary registration that was added in 4.6.63.

http://imgur.com/a/rBv9T

**Comment by Modbder** [comment]
Open Computers had a bug(I believe they fixed that yesterday) with their recipes(see #28 ). EC3 adds it's glass,stone and chests to the ore dictionary - that is intentional, and works fine with other mods.

**Comment by ligerzero459** [comment]
:+1: My mistake, should've checked the closed issues too :grin:
