### ISSUE TITLE
Voidstone Recipe Broken

### ISSUE THREAD

**Issue by goreae** [Modbder/EssentialCraft3#56]
RecipeRegistry.java, line 1192. "titanite" is misspelled "ttitanite". Makes the recipe show up as four obsidian plates in a cross pattern rather than 5 titanite and 4 obsidian plates in a TNT pattern in the book and makes the recipe just not work at all.

**Comment by DArkHekRoMaNT** [comment]
The mod is abandoned, the author disappeared several years ago.

**Comment by goreae** [comment]
Yeah wrong github whoops. It's broke in EC4 too.
