### ISSUE TITLE
Machines able to reach negative power

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Modbder/EssentialCraft3#8]
Forge: 10.13.3.1428
Essential craft 3: 4.5.1710.222
Dummy core:1.13

As seen in these screen shots, some machines are able to reach a negative power level should they ever run out of power

http://i.imgur.com/R7YbJIG.png

http://i.imgur.com/xzdFafE.png.

**Comment by Modbder** [comment]
Does the bug affect gameplay at all? I mean, the devices with negative power are not functional, right? This might be just a simple tiny client desync, or just a tiny bug in the code. I do not think, that it is really a big issue, is it?

**Comment by TheMadmanofChaos** [comment]
They don't function, and it isn't a huge issue. I have the mantra of "If it seems like a bug or unintended, report it. Then the Dev is able to choose if it is a real issue or not and address it as such."  Some like cleaning up little issues like this, others don't. Not my place to choose on this matter, as it isn't my mod.

And a quick log out, then back into the world shows it is not a client de-sync.
