### ISSUE TITLE
Magmatic smeltery always quadruples ore

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Modbder/EssentialCraft3#9]
Forge: 10.13.3.1428
Essential craft 3: 4.5.1710.222
Dummy core:1.13

The magmatic smeltery is ignoring the config option(I have it at the default 0.33) and always producing four ingots per process. This was tested with half a stack of iron, to rule out luck. Two stacks of ingots were collected.

**Comment by Modbder** [comment]
It was a change in one of the latest versions, due to Magmatic Furnaces being introduced. They work as ore doubling now, where the smeltery works as ore quadrupling.

**Comment by TheMadmanofChaos** [comment]
Ah, alright. might I request that the chance is kept, but it defaults to 1.0 in the configs so a pack maker can lower the odds?

Also, the book might need a few touch ups to correct this error.
